#!/bin/bash

# Huntly v0.4.8 Release Creation Instructions
# This script provides instructions for manually creating the v0.4.8 GitHub release

echo "=============================================="
echo "Huntly v0.4.8 Release Creation Instructions"
echo "=============================================="
echo ""
echo "1. Navigate to GitHub Releases page:"
echo "   https://github.com/lcomplete/huntly/releases"
echo ""
echo "2. Click 'Draft a new release'"
echo ""
echo "3. Fill in the release form:"
echo "   - Tag version: v0.4.8"
echo "   - Release title: v0.4.8"
echo "   - Target: main (should auto-select based on existing tag)"
echo ""
echo "4. Copy the release body from: RELEASE_BODY_v0.4.8.md"
echo "   (Content is shown below)"
echo ""
echo "=============================================="
echo "RELEASE BODY CONTENT:"
echo "=============================================="
cat RELEASE_BODY_v0.4.8.md
echo ""
echo "=============================================="
echo ""
echo "5. Set as draft release initially"
echo ""
echo "6. The automated workflow should have already built and uploaded:"
echo "   - huntly-server-0.4.8.jar"
echo "   - huntly-client-0.4.8.zip" 
echo "   - huntly-browser-extension-0.4.8.zip"
echo ""
echo "7. Review the release and publish when ready"
echo ""
echo "Note: The v0.4.8 tag already exists in the repository."
echo "If the automated workflow ran, check if there's already a draft release."