package com.huntly.server.domain.model.tweet;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;

import java.util.ArrayList;

/**
 * Auto generated by https://json2csharp.com/
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class TweetsRoot {

    public Data data;

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class AdditionalMediaInfo {
        public boolean monetizable;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class AffiliatesHighlightedLabel {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Attributes {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class BoundingBox {
        public ArrayList<ArrayList<ArrayList<Double>>> coordinates;
        public String type;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class BusinessAccount {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Category {
        public int id;
        public String name;
        public String icon_name;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ClientEventInfo {
        public String component;
        public Details details;
        public String entityToken;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Content {
        public String entryType;
        public String __typename;
        public ArrayList<Item> items;
        public Metadata metadata;
        public String displayType;
        public ClientEventInfo clientEventInfo;
        public FeedbackInfo feedbackInfo;
        public ItemContent itemContent;
        public String value;
        public String cursorType;
        public boolean stopOnEmptyResponse;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ConversationMetadata {
        public ArrayList<String> allTweetIds;
        public boolean enableDeduplication;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Core {
        public UserResults user_results;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Data {
        public Home home;

        public List list;
        
        public Timeline threaded_conversation_with_injections_v2;

        public BookmarkTimeline bookmark_timeline;

        public Viewer viewer;
        
        public User user;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class User{
        public UserResult result;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class UserResult{
        public TimelineV2 timeline_v2;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class TimelineV2{
        public Timeline timeline;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Viewer {
        public CommunitiesTimeline communities_timeline;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class CommunitiesTimeline {
        public Timeline timeline;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class BookmarkTimeline {
        public Timeline timeline;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class List {
        public Timeline tweets_timeline;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Description {
        public ArrayList<Url> urls;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Details {
        public TimelinesDetails timelinesDetails;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class EditControl {
        public ArrayList<String> edit_tweet_ids;
        public String editable_until_msecs;
        public boolean is_edit_eligible;
        public String edits_remaining;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class EditPerspective {
        public boolean favorited;
        public boolean retweeted;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Entities {
        public Description description;
        public Url url;
        public ArrayList<Medium> media;
        public ArrayList<UserMention> user_mentions;
        public ArrayList<Url> urls;
        public ArrayList<Hashtag> hashtags;
        public ArrayList<Object> symbols;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Entry {
        public String entryId;
        public String sortIndex;
        public Content content;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ExtendedEntities {
        public ArrayList<Medium> media;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ExtMediaAvailability {
        public String status;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ExtMediaColor {
        public ArrayList<Palette> palette;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Face {
        public int x;
        public int y;
        public int h;
        public int w;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Features {
        public Large large;
        public Medium medium;
        public Small small;
        public Orig orig;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class FeedbackAction {
        public String key;
        public Value value;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class FeedbackInfo {
        public ArrayList<String> feedbackKeys;
        public String feedbackMetadata;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class FocusRect {
        public int x;
        public int y;
        public int w;
        public int h;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Hashtag {
        public ArrayList<Integer> indices;
        public String text;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Home {
        public Timeline home_timeline_urt;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Timeline {
        public Timeline timeline;
        public ArrayList<Instruction> instructions;
        public ResponseObjects responseObjects;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Instruction {
        public String type;
        public ArrayList<Entry> entries;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Item {
        public String entryId;
        public boolean dispensable;
        public ItemDetail item;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ItemDetail {
        public ItemContent itemContent;
        public FeedbackInfo feedbackInfo;
        public ClientEventInfo clientEventInfo;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ItemContent {
        public String itemType;
        public String __typename;
        public TweetResults tweet_results;
        public String tweetDisplayType;
        public SocialContext socialContext;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class LandingUrl {
        public String url;
        public String urlType;
        public UrtEndpointOptions urtEndpointOptions;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Large {
        public ArrayList<Face> faces;
        public int h;
        public int w;
        public String resize;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Legacy {
        public boolean blocked_by;
        public boolean blocking;
        public boolean follow_request_sent;
        public boolean followed_by;
        public boolean following;
        public boolean muting;
        public boolean notifications;
        @JsonProperty("protected")
        public boolean myprotected;
        public boolean can_dm;
        public boolean can_media_tag;
        public String created_at;
        public boolean default_profile;
        public boolean default_profile_image;
        public String description;
        public Entities entities;
        public int fast_followers_count;
        public int favourites_count;
        public int followers_count;
        public int friends_count;
        public boolean has_custom_timelines;
        public boolean is_translator;
        public int listed_count;
        public String location;
        public int media_count;
        public String name;
        public int normal_followers_count;
        public ArrayList<String> pinned_tweet_ids_str;
        public boolean possibly_sensitive;
        public ProfileBannerExtensions profile_banner_extensions;
        public String profile_banner_url;
        public ProfileImageExtensions profile_image_extensions;
        public String profile_image_url_https;
        public String profile_interstitial_type;
        public String screen_name;
        public int statuses_count;
        public String translator_type;
        public String url;
        public boolean verified;
        public boolean want_retweets;
        public ArrayList<Object> withheld_in_countries;
        public String conversation_id_str;
        public ArrayList<Integer> display_text_range;
        public ExtendedEntities extended_entities;
        public int favorite_count;
        public boolean favorited;
        public String full_text;
        public boolean is_quote_status;
        public String lang;
        public boolean possibly_sensitive_editable;
        public int quote_count;
        public int reply_count;
        public int retweet_count;
        public boolean retweeted;
        public String user_id_str;
        public String id_str;
        public SelfThread self_thread;
        public String quoted_status_id_str;
        public QuotedStatusPermalink quoted_status_permalink;
        public String in_reply_to_screen_name;
        public String in_reply_to_status_id_str;
        public String in_reply_to_user_id_str;
        public String verified_type;
        public Place place;
        public RetweetedStatusResult retweeted_status_result;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class MediaColor {
        public R r;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class MediaStats {
        public int viewCount;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Medium {
        public String display_url;
        public String expanded_url;
        public String id_str;
        public ArrayList<Integer> indices;
        public String media_url_https;
        public String type;
        public String url;
        public Features features;
        public Sizes sizes;
        public OriginalInfo original_info;
        public String media_key;
        public ExtMediaColor ext_media_color;
        public ExtMediaAvailability ext_media_availability;
        public AdditionalMediaInfo additional_media_info;
        public MediaStats mediaStats;
        public VideoInfo video_info;
        public String ext_alt_text;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Medium11 {
        public ArrayList<Face> faces;
        public int h;
        public int w;
        public String resize;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Metadata {
        public ConversationMetadata conversationMetadata;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Ok {
        public ArrayList<Palette> palette;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Orig {
        public ArrayList<Face> faces;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class OriginalInfo {
        public int height;
        public int width;
        public ArrayList<FocusRect> focus_rects;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Palette {
        public double percentage;
        public Rgb rgb;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Place {
        public Attributes attributes;
        public BoundingBox bounding_box;
        public ArrayList<Object> contained_within;
        public String country;
        public String country_code;
        public String full_name;
        public String name;
        public String id;
        public String place_type;
        public String url;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Professional {
        public String rest_id;
        public String professional_type;
        public ArrayList<Category> category;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ProfileBannerExtensions {
        public MediaColor mediaColor;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ProfileImageExtensions {
        public MediaColor mediaColor;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class QuotedRefResult {
        public Result result;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class QuotedStatusPermalink {
        public String url;
        public String expanded;
        public String display;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class QuotedStatusResult {
        public Result result;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RetweetedStatusResult {
        public Result result;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class R {
        public Ok ok;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class RequestParam {
        public String key;
        public String value;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class ResponseObjects {
        public ArrayList<FeedbackAction> feedbackActions;
        public ArrayList<Object> immediateReactions;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Result {
        
        public Result tweet;
        public String __typename;
        public String rest_id;
        public Core core;
        public UnmentionData unmention_data;
        public EditControl edit_control;
        public EditPerspective edit_perspective;
        public boolean is_translatable;
        public Views views;
        public String source;
        public QuotedStatusResult quoted_status_result;
        public Legacy legacy;
        public String id;
        public AffiliatesHighlightedLabel affiliates_highlighted_label;
        public boolean has_graduated_access;
        public boolean is_blue_verified;
        public boolean has_nft_avatar;
        public boolean super_follow_eligible;
        public boolean super_followed_by;
        public boolean super_following;
        public BusinessAccount business_account;
        public Professional professional;
        public QuotedRefResult quotedRefResult;
        
        public Card card;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Card{
        public String rest_id;
        public CardLegacy legacy;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class CardLegacy{
        public JsonNode binding_values;
        
        public String name;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Rgb {
        public int blue;
        public int green;
        public int red;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Root {
        public Data data;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class SelfThread {
        public String id_str;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Sizes {
        public Large large;
        public Medium medium;
        public Small small;
        public Thumb thumb;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Small {
        public ArrayList<Face> faces;
        public int h;
        public int w;
        public String resize;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class SocialContext {
        public String type;
        public String contextType;
        public String text;
        public LandingUrl landingUrl;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Thumb {
        public int h;
        public int w;
        public String resize;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class UrtEndpointOptionsTimeline {
        public String id;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class TimelinesDetails {
        public String injectionType;
        public String controllerData;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class TweetResults {
        public Result result;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class UnmentionData {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Url {
        public String display_url;
        public String expanded_url;
        public String url;
        public ArrayList<Integer> indices;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Url11 {
        public ArrayList<Url> urls;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class UrtEndpointOptions {
        public String title;
        public ArrayList<RequestParam> requestParams;
        public UrtEndpointOptionsTimeline timeline;
        public String cacheId;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class UserMention {
        public String id_str;
        public String name;
        public String screen_name;
        public ArrayList<Integer> indices;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class UserResults {
        public Result result;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Value {
        public String feedbackType;
        public String prompt;
        public String confirmation;
        public String feedbackUrl;
        public String encodedFeedbackRequest;
        public boolean hasUndoAction;
        public ArrayList<String> childKeys;
        public String icon;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Variant {
        public int bitrate;
        public String content_type;
        public String url;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class VideoInfo {
        public ArrayList<Integer> aspect_ratio;
        public int duration_millis;
        public ArrayList<Variant> variants;
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Views {
        public String count;
        public String state;
    }


}

