export type SORT_VALUE = 'ARCHIVED_AT' | 'COLLECTED_AT' | 'CONNECTED_AT' | 'CREATED_AT' | 'LAST_READ_AT' | 'READ_LATER_AT' | 'SAVED_AT' | 'STARRED_AT' | 'VOTE_SCORE';

export type ContentType = 'BROWSER_HISTORY' | 'MARKDOWN'| 'QUOTED_TWEET' | 'TWEET';